### ISSUE TITLE
try

### ISSUE THREAD

**Issue by zhangyl52** [zhiqiang21/WebComponent#1]
baidu browser is work ok, but inTencent browser it not work,just call the systerm picture file explore.I want to know why

**Comment by zhiqiang21** [comment]
sorry ,this demo is for mobile not pc browser

**Comment by zhiqiang21** [comment]
i test qq browser ,it's work ok !  can i know what version you use QQ browser

![2016-02-15 16_52_36](https://cloud.githubusercontent.com/assets/3990411/13043693/9ac01994-d404-11e5-9aeb-8e9e776bf6ef.gif)
