### ISSUE TITLE
请问Number中逗号是什么意思？

### ISSUE THREAD

**Issue by lann1986** [zhiqiang21/WebComponent#2]
跑马灯组件：Number($(prizeList[i]).attr('grade-value'), _this.LightArea)
你好，请问Number中的逗号是做什么的呢？这个函数可以多参数吗？没百度到答案，请教一下，还望指点。

**Comment by zhiqiang21** [comment]
非常抱歉，这里是我代码的问题。 我这里是想要这样写的

``` javascript
if (Number($(prizeList[i], _this.LightArea).attr('grade-value')) === _this.prizeGradeId) {
}
```

但是在代码中确出现了问题，因为浏览器没有报错，就没有发现这个代码 bug  。源代码已经做了修改。感谢您的反馈

浏览器没有报错的信息如下：
![qq20160217-0](https://cloud.githubusercontent.com/assets/3990411/13108288/1583292e-d5ad-11e5-989a-368c66d2884d.png)

**Comment by lann1986** [comment]
感谢答复。

关于Array.From()，请问有详细的解释吗？该如何查找相关资料？在w3shool/com/cn没能找到相关解释，还望指点。不胜感激。

**Comment by zhiqiang21** [comment]
你可以参考这个文档：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/from

https://developer.mozilla.org/zh-CN/
这个网站是比较权威和全面的前端开发文档，可以收藏一下

**Comment by lann1986** [comment]
@zhiqiang21 :) 十分感谢。。

**Comment by zhiqiang21** [comment]
如果解决了你的问题，请关闭此问题，谢谢。。。
