### ISSUE TITLE
html5-qrcode相关问题请教

### ISSUE THREAD

**Issue by ZengYJ** [zhiqiang21/WebComponent#3]
文档里面介绍说能在浏览器里面调用摄像头，但是没有看到相应的事例代码；只有选择文件进行二维码解析的。请教下在微信浏览器里面怎么调用摄像头进行二维码扫码。 我QQ:383957467.麻烦加下

**Comment by zhiqiang21** [comment]
我这里使用的是`<input type="file">` 标签，这个标签在移动端默认会呼起系统的相册和摄像选择框，你可以选择从相册选择一张图片，也可以使用照相机拍一张。

但是这样做会有些坑。请看详细的文档：[https://github.com/zhiqiang21/WebComponent/blob/master/html5-Qrcode/README.md](https://github.com/zhiqiang21/WebComponent/blob/master/html5-Qrcode/README.md)

这里建议查下微信的api，看看有没有api通过微信的客户端调取系统的摄像头。
